version: "3.9"
networks:
  network:
    driver: bridge

services:
  terms_go:
    build: .

    container_name: terms_go
    ports:
      - "8080:8080"
    networks:
      - network
    user: root
    restart: on-failure