version: "3.9"
networks:
  network:
    driver: bridge

services:
  terms_rust:
    build: .

    container_name: terms_rust
    ports:
      - "8088:8088"
    networks:
      - network
    user: root
    restart: on-failure